name: Pruebas E2E
on: [push, pull_request]
jobs:
  e2e:
    runs-on: ubuntu-latest
    env:
      HEADLESS: "1"
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Debug repo files
        run: ls -la

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest ./ --html=reporte.html --self-contained-html

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: reporte
          path: reporte.html